name: Secrets workflow

# These are the veriables which you could use in your workflows
env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

on:
  pull_request:
    branches: ["main"]
     

jobs:
  secrets:
    name: Secrets Demo 
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "$API_CSPROJ_PATH is value ${{ secrets.SECRET_API_KEY }}" 
     
        


    